baseURL = "/"
languageCode = "en-gb"
title = "Janice Rolnick Educational Consultant"
buildDrafts = false

enableRobotsTXT = true
disableAliases = true
hrefTargetBlank = true

[params]
disallow_search_engines = false # set robots.txt to disallow everything

# add redirects/headers
[outputs]
Home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true


# Menus
sectionPagesMenu = "primary"
[[menu.primary]]
    name = "Home"
    weight = -5000
    identifier = ""
    url = "/"
[[menu.primary]]
    name = "Testimonials"
    weight = -4000
    identifier = "testimonials"
    url = "/testimonials/"
[[menu.primary]]
    name = "Services for Schools"
    weight = -4000
    identifier = "services"
    url = "/services/"
[[menu.primary]]
    name = "Dyslexia"
    weight = -3000
    identifier = "dyslexia"
    url = "/dyslexia/"
[[menu.primary]]
    name = "Assessment"
    weight = -3000
    identifier = "assessment"
    url = "/assessment/"
[[menu.primary]]
    name = "Downloads"
    weight = -2000
    identifier = "downloads"
    url = "/downloads/"
